<?php
print "<!DOCTYPE html>\n";
print "<!--\n";
print "This is a starter template page. Use this page to start your new project from\n";
print "scratch. This page gets rid of all links and provides the needed markup only.\n";
print "-->\n";
print "<html>\n";
print "<head>\n";
print "  <meta charset=\"utf-8\">\n";
print "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
print "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
print "  <title>Eagle Events | Sign Up</title>\n";
print "  <!-- Tell the browser to be responsive to screen width -->\n";
print "  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\n";
print "  <link rel=\"stylesheet\" href=\"bower_components/bootstrap/dist/css/bootstrap.min.css\">\n";
print "  <!-- Font Awesome -->\n";
print "  <link rel=\"stylesheet\" href=\"bower_components/font-awesome/css/font-awesome.min.css\">\n";
print "  <!-- Ionicons -->\n";
print "  <link rel=\"stylesheet\" href=\"bower_components/Ionicons/css/ionicons.min.css\">\n";
print "  <!-- Theme style -->\n";
print "  <link rel=\"stylesheet\" href=\"dist/css/AdminLTE.min.css\">\n";
print "  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter\n";
print "        page. However, you can choose any other skin. Make sure you\n";
print "        apply the skin class to the body tag so the changes take effect. -->\n";
print "  <link rel=\"stylesheet\" href=\"dist/css/skins/skin-blue.min.css\">\n";
print "\n";
print "  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n";
print "  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n";
print "  <!--[if lt IE 9]>\n";
print "  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n";
print "  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n";
print "  <![endif]-->\n";
print "\n";
print "  <!-- Google Font -->\n";
print "  <link rel=\"stylesheet\"\n";
print "        href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic\">\n";
print "</head>\n";
print "<!--\n";
print "BODY TAG OPTIONS:\n";
print "=================\n";
print "Apply one or more of the following classes to get the\n";
print "desired effect\n";
print "|---------------------------------------------------------|\n";
print "| SKINS         | skin-blue                               |\n";
print "|               | skin-black                              |\n";
print "|               | skin-purple                             |\n";
print "|               | skin-yellow                             |\n";
print "|               | skin-red                                |\n";
print "|               | skin-green                              |\n";
print "|---------------------------------------------------------|\n";
print "|LAYOUT OPTIONS | fixed                                   |\n";
print "|               | layout-boxed                            |\n";
print "|               | layout-top-nav                          |\n";
print "|               | sidebar-collapse                        |\n";
print "|               | sidebar-mini                            |\n";
print "|---------------------------------------------------------|\n";
print "-->\n";
print "<body class=\"hold-transition skin-blue sidebar-mini\">\n";
print "<div class=\"wrapper\">\n";
print "\n";
print "  <!-- Main Header -->\n";
print "  <header class=\"main-header\">\n";
print "\n";
print "    <!-- Logo -->\n";
print "    <a href=\"#\" class=\"logo\">\n";
print "      <!-- mini logo for sidebar mini 50x50 pixels -->\n";
print "      <span class=\"logo-mini\"><b>E</b>LE</span>\n";
print "      <!-- logo for regular state and mobile devices -->\n";
print "      <span class=\"logo-lg\"><b>Eagle</b>Events</span>\n";
print "    </a>\n";
print "\n";
print "    <!-- Header Navbar -->\n";
print "    <nav class=\"navbar navbar-static-top\" role=\"navigation\">\n";
print "  </header>\n";
print "\n";
print "  <!-- Content Wrapper. Contains page content -->\n";
print "  <div class=\"content-wrapper\">\n";
print "    <!-- Content Header (Page header) -->\n";
print "    <section class=\"content-header\">\n";
print "      <h1>\n";
print "        Welcome to Eagle Events! Please sign up below.\n";
print "        <small>Get notified about Emory events!</small>\n";
print "      </h1>\n";
print "    </section>\n";
print "\n";
print "    <!-- Main content -->\n";
print "    <section class=\"content container-fluid\">\n";
print "\n";
print "      <!--------------------------\n";
print "        | Your Page Content Here |\n";
print "        -------------------------->\n";
print "\n";
print "        <div class=\"container\">\n";
print "     <h3>\n";
print "\n";
print "     </h5>\n";
print "        <form action = \"SignUpEcho.php\" method = \"POST\">\n";
print "          <br><br>\n";
print "          <div class=\"form-row\">\n";
print "            <div class=\"col\">\n";
print "              <label for=\"username\">Username</label>\n";
print "              <input type=\"text\" name = \"username\" class=\"form-control\" placeholder=\"Username\" required>\n";
print "            </div>\n";
print "          </div>\n";
print "          <br><br>\n";
print "          <div class=\"form-row\">\n";
print "            <div class=\"col\">\n";
print "              <label for=\"password\">Password</label>\n";
print "              <input type=\"PASSWORD\" name = \"password\" class=\"form-control\" placeholder=\"Password\" required>\n";
print "            </div>\n";
print "          </div>\n";
print "          <br><br>\n";
print "          <div class=\"form-row\">\n";
print "            <div class=\"col\">\n";
print "              <label for=\"password\">Re-enter Password</label>\n";
print "              <input type=\"PASSWORD\" name = \"password\" class=\"form-control\" placeholder=\"Password\" required>\n";
print "            </div>\n";
print "          </div>\n";
print "          <br><br>\n";
print "          <div class=\"form-row\">\n";
print "            <div class=\"col\">\n";
print "              <label for=\"email\">Email</label>\n";
print "              <input type=\"text\" name = \"email\" class=\"form-control\" placeholder=\"Email\" required>\n";
print "            </div>\n";
print "          </div>\n";
print "          <br><br>\n";
print "          <div class=\"form-row\">\n";
print "            <div class=\"col\">\n";
print "              <label for=\"fname\">First Name</label>\n";
print "              <input type=\"text\" name = \"fname\" class=\"form-control\" placeholder=\"First Name\" required>\n";
print "            </div>\n";
print "          </div>\n";
print "          <br><br>\n";
print "          <div class=\"form-row\">\n";
print "            <div class=\"col\">\n";
print "              <label for=\"lname\">Last Name</label>\n";
print "              <input type=\"text\" name = \"lname\" class=\"form-control\" placeholder=\"Last Name\" required>\n";
print "            </div>\n";
print "          </div>\n";
print "          <br><br>\n";
print "          <div class=\"form-row\">\n";
print "              <label class=\"custom-control-label\" for=\"year\">Year</label><br>\n";
print "              <div class=\"custom-control custom-radio\">\n";
print "                <input type=\"radio\" class=\"custom-control-input\" id=\"Freshman\" name=\"year\" required>\n";
print "                <label class=\"custom-control-label\" for=\"Freshman\">Freshman</label>\n";
print "              </div>\n";
print "              <div class=\"custom-control custom-radio\">\n";
print "                <input type=\"radio\" class=\"custom-control-input\" id=\"Sophomore\" name=\"year\" required>\n";
print "                <label class=\"custom-control-label\" for=\"Sophomore\">Sophomore</label>\n";
print "              </div>\n";
print "              <div class=\"custom-control custom-radio\">\n";
print "                <input type=\"radio\" class=\"custom-control-input\" id=\"Junior\" name=\"year\" required>\n";
print "                <label class=\"custom-control-label\" for=\"Junior\">Junior</label>\n";
print "              </div>\n";
print "              <div class=\"custom-control custom-radio\">\n";
print "                <input type=\"radio\" class=\"custom-control-input\" id=\"Senior\" name=\"year\" required>\n";
print "                <label class=\"custom-control-label\" for=\"Senior\">Senior</label>\n";
print "              </div>\n";
print "              <div class=\"custom-control custom-radio\">\n";
print "                <input type=\"radio\" class=\"custom-control-input\" id=\"Graduate\" name=\"year\" required>\n";
print "                <label class=\"custom-control-label\" for=\"Graduate\">Graduate</label>\n";
print "              </div>\n";
print "          <br><br>\n";
print "          <button type = \"submit\" class = \"btn btn-primary\"> Submit </button>\n";
print "        </form>\n";
print "     </h5>\n";
print "   </div>\n";
print "\n";
print "    </section>\n";
print "    <!-- /.content -->\n";
print "  </div>\n";
print "  <!-- /.content-wrapper -->\n";
print "\n";
print "  <!-- Main Footer -->\n";
print "  <footer class=\"main-footer\">\n";
print "    <!-- To the right -->\n";
print "    <!-- Default to the left -->\n";
print "    <strong>Copyright © 2018 <a href=\"#\">EagleEvents</a>.</strong> All rights reserved.\n";
print "  </footer>\n";
print "\n";
print "  <!-- /.control-sidebar -->\n";
print "  <!-- Add the sidebar's background. This div must be placed\n";
print "  immediately after the control sidebar -->\n";
print "<!-- ./wrapper -->\n";
print "\n";
print "<!-- REQUIRED JS SCRIPTS -->\n";
print "\n";
print "<!-- jQuery 3 -->\n";
print "<script src=\"bower_components/jquery/dist/jquery.min.js\"></script>\n";
print "<!-- Bootstrap 3.3.7 -->\n";
print "<script src=\"bower_components/bootstrap/dist/js/bootstrap.min.js\"></script>\n";
print "<!-- AdminLTE App -->\n";
print "<script src=\"dist/js/adminlte.min.js\"></script>\n";
print "\n";
print "<!-- Optionally, you can add Slimscroll and FastClick plugins.\n";
print "     Both of these plugins are recommended to enhance the\n";
print "     user experience. -->\n";
print "</body>\n";
print "</html>\n";
?>
